package modelo.entidad;
// Generated 10-31-2022 09:38:31 PM by Hibernate Tools 4.3.1



/**
 * Ingenieros generated by hbm2java
 */
public class Ingenieros  implements java.io.Serializable {


     private Integer idIng;
     private String nombre;
     private String apellido;
     private String tipo;
     private int edad;
     private String carnet;

    public Ingenieros() {
    }

    public Ingenieros(String nombre, String apellido, String tipo, int edad, String carnet) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.tipo = tipo;
       this.edad = edad;
       this.carnet = carnet;
    }
   
    public Integer getIdIng() {
        return this.idIng;
    }
    
    public void setIdIng(Integer idIng) {
        this.idIng = idIng;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getCarnet() {
        return this.carnet;
    }
    
    public void setCarnet(String carnet) {
        this.carnet = carnet;
    }




}


